TwitterAPI導入からteacherDataの表示 #41
camp-team/school-potal pull request #94
Opened 2020-07-15 17:16 UTC by yusukegunji

死ぬほど遅くなりましてすみません。
以下の作業を完了しましたのでご確認宜しくお願いいたします。

## Detail

- [x] 記事一覧、記事詳細の表示におけるローディングUI追加 #41 
- [x] twitterログイン実装 #32 
- [x] プライバシー画面/privacy #68
- [x] twitterアカウントのメンバー表示 #45

## Next

- [ ] 検索機能実装 #85

fixed #41 #32 #68 #45

2020-07-15 22:33 UTC, dninomiya requested changes

2020-07-15 22:33 UTC, deerboy commented on firestore.rules
> +      allow update: if request.auth.uid == '8w4yczmaTqcqX8YxvrIlGpg96Vf2' || request.auth.uid == '3B0SHPilaSdK1IMBAgl455Zp8gN2';
adminだけに絞ってる意図だと思いますが、本番環境と開発環境は分ける前提で（かつ、将来的に複数スタッフが存在するかもなので）、対象ユーザーのデータにisAdmin: true が含まれるかどうかを判断基準にしましょう

https://to.camp/lesson?v=Ek2gwGhr9bcj26ufeq64

2020-07-15 22:33 UTC, deerboy commented on src/app/article-detail/article/article.component.html
> +    <div class="menta">
mentor

2020-07-15 22:33 UTC, deerboy commented on src/app/article-detail/article/article.component.html
> +      <div *ngIf="teachers$ | async as teachers; else zero">
変数名とクラスメイに統一感がないのでteacherかmentorに絞りたい
zeroは値なので、blankやnoTeachersなど状態を表す命名にしたい

2020-07-15 22:33 UTC, deerboy commented on functions/src/twitter.function.ts
> +          profile_image_url: TwitterProfile.profile_image_url_https,
キャメルケース

2020-07-15 22:33 UTC, deerboy commented on src/app/article-edit/edit/edit.component.html
> +        <!-- <div formArrayName="teacherIds">
TODOなき謎のコメントアウトは残さない

2020-07-15 22:33 UTC, deerboy commented on src/app/intl/privacy/privacy.component.html
> +<section>
今回は良いですが、本PRに関係ないコミットは本来は混ぜて欲しくないです

2020-07-15 22:33 UTC, deerboy commented on src/app/login/login/login.component.scss
> +    &--g {
省略しすぎで意味がわからないので google、twitterなどとしたい

2020-07-15 22:33 UTC, deerboy commented on src/app/services/user.service.ts
> +              });
必要？

2020-07-15 22:33 UTC, deerboy commented on src/app/services/user.service.ts
> +      .subscribe(async (doc) => {
asyncを活かして並列にしたい。subscribeのなかでPromise処理は見通しが悪くリスクが大きいので避ける

```ts
const isExists = (await this.db.doc(`...`).get().toPromise()).exists;
if (!isExists) {
  ...
}
```

2020-07-16 03:52 UTC, yusukegunji commented on src/app/intl/privacy/privacy.component.html
> +<section>
すみません！Twitterのemailデータを取得するのに必要になったため、急遽追加しました...。

2020-07-16 04:15 UTC, yusukegunji commented
チェックありがとうございました！
以下の修正を対応しましたので、再度ご確認宜しくお願いいたします。

- [x] firestoreルール修正（→isAdmin: true）
- [x] 変数名とクラス名の統一
- [x] プロパティ名修正（→キャメルケース）
- [x] modifier名修正
- [x] コメントアウト撤去
- [x] twitterトークン取得関数撤去

2020-07-16 04:31 UTC, dninomiya approved these changes
GJ!!

2020-07-16 04:31 UTC, merged